[colors.primary]
background = '#171a1d'
foreground = '#c5c5c6'

[colors.normal]
black   = '#171a1d'
red     = '#788696'
green   = '#788696'
yellow  = '#788696'
blue    = '#788696'
magenta = '#788696'
cyan    = '#788696'
white   = '#c5c5c6'

[colors.bright]
black   = '#515355'
red     = '#788696'
green   = '#788696'
yellow  = '#788696'
blue    = '#788696'
magenta = '#788696'
cyan    = '#788696'
white   = '#c5c5c6'
